name: Metrics
on:
  schedule: [{cron: "0 */24 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_CI }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # activity calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # PRs and issues
          plugin_followup: yes
          plugin_followup_indepth: yes

          # Bio
          plugin_introduction: yes
          plugin_activity_days: 0

          # code lines
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_history_limit: 0

          # languages
          plugin_languages: yes
          plugin_languages_colors: rainbow
          plugin_languages_details: bytes-size, percentage, lines

          # achievments          
          plugin_achievements: yes
          plugin_achievements_secrets: true
          plugin_achievements_display: detailed

          # commit calendar
          plugin_calendar: yes
          plugin_calendar_limit: 0

          # work time and tools
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
