name: Metrics
on:
  schedule: [{cron: "0 */24 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_CI }}
          plugin_lines: yes
          base_indepth: yes
          plugin_licenses: yes
          plugin_isocalendar: yes
          filename: metrics.svg
          plugin_lines_repositories_limit: 100
          plugin_isocalendar_duration: full-year
          repositories_affiliations: owner, collaborator

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_CI }}
          base: ''
          base_indepth: yes
          plugin_achievements: yes
          plugin_achievements_secrets: true
          plugin_fortune: yes
          plugin_achievements_display: compact
          filename: metrics.achievements.svg
          repositories_affiliations: owner, collaborator

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_CI }}
          base_indepth: yes
          base: ''
          plugin_languages: yes
          repositories_affiliations: owner
          filename: metrics.languages.svg
          plugin_languages_colors: rainbow
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage, lines
