name: Metrics
on:
  schedule: [{cron: "0 */24 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_CI }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_followup: yes
          plugin_activity_days: 0
          plugin_lines: yes
          plugin_languages: yes
